services:
  fasteats_db_postgres:
    image: postgres:latest
    container_name: fasteats_db_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - fasteats_pgdata:/var/lib/postgresql/data
    networks:
      - fasteats_network

  fasteats_rabbitmq:
    image: rabbitmq:management
    container_name: fasteats_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - fasteats_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fasteats_network

  fasteats_redis:
    image: redis:latest
    container_name: fasteats_redis
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - fasteats_redis_data:/data
    networks:
      - fasteats_network

networks:
  fasteats_network:

volumes:
  fasteats_pgdata:
  fasteats_rabbitmq_data:
  fasteats_redis_data:
