services:
  order_service_db:
    image: postgres:latest
    container_name: order_service_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - order_pgdata:/var/lib/postgresql/data

volumes:
  order_pgdata: