services:
  user_service_db:
    image: postgres:latest
    container_name: user_service_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - user_pgdata:/var/lib/postgresql/data

volumes:
  user_pgdata:
